from python_translators.translators.google_translator import GoogleTranslator
#from python_translators.translators.best_effort_translator import BestEffortTranslator
#from python_translators.translators.collins_translator import CollinsTranslator
#from python_translators.translators.microsoft_translator import MicrosoftTranslator
